// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "stevekingford@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/collection": {
            "get": {
                "description": "获取分页列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "分页列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页条数",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "创建信息",
                "parameters": [
                    {
                        "description": "创建信息",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.CreateService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            }
        },
        "/api/collection-category": {
            "get": {
                "description": "获取分页列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Collection-Category"
                ],
                "summary": "分页列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页条数",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection-Category"
                ],
                "summary": "创建信息",
                "parameters": [
                    {
                        "description": "创建信息",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/category.CreateService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            }
        },
        "/api/collection-category/{id}": {
            "get": {
                "description": "通过id获取信息",
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "Collection-Category"
                ],
                "summary": "通过Id获取信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主键id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "通过id修改信息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Collection-Category"
                ],
                "summary": "通过id修改信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主键id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改信息",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/category.UpdateService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "通过id删除信息",
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "Collection-Category"
                ],
                "summary": "通过id删除信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主键id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            }
        },
        "/api/collection/{id}": {
            "get": {
                "description": "通过id获取信息",
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "通过Id获取信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主键id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "通过id修改信息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "通过id修改信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主键id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改信息",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.UpdateService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "通过id删除信息",
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "通过id删除信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主键id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    },
                    "400": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/global.Response"
                        }
                    }
                }
            }
        },
        "/system/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "用户登录",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "用户注册",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取用户列表",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/user/:id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取用户列表",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "修改用户信息",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "删除用户信息",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "category.CreateService": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "category.UpdateService": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "collection.CreateService": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "collection.UpdateService": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "global.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "error": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "Swagger kingford backend API",
	Description: "This is a kingford backend  server Petstore server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
