definitions:
  collection.CreateService:
    properties:
      title:
        type: string
    type: object
  collection.UpdateService:
    properties:
      title:
        type: string
    type: object
  dto.Response:
    properties:
      data:
        type: object
      error:
        type: string
      msg:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/collection:
    get:
      consumes:
      - application/json
      description: 获取分页列表
      parameters:
      - description: 当前页
        in: query
        name: pageIndex
        type: integer
      - description: 分页条数
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: 失败
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 分页列表
      tags:
      - Collection
    post:
      description: 创建信息
      parameters:
      - description: 创建信息
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/collection.CreateService'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: 失败
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 创建信息
      tags:
      - Collection
  /api/v1/collection/{id}:
    delete:
      consumes:
      - application/x-json-stream
      description: 删除通过id信息
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: 失败
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 删除通过id信息
      tags:
      - Collection
    get:
      consumes:
      - application/x-json-stream
      description: 通过id获取信息
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: 失败
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 通过Id获取信息
      tags:
      - Collection
    put:
      consumes:
      - application/json
      description: 通过id修改信息
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: 修改信息
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/collection.UpdateService'
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: 失败
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 通过id修改信息
      tags:
      - Collection
  /system/login:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - System
  /system/register:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - System
  /system/user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - System
  /system/user/:id:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 删除用户信息
      tags:
      - System
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - System
    put:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 修改用户信息
      tags:
      - System
swagger: "2.0"
